/* RAS_Err.c */
#include "RAS_Inc.h"

char* ERR_GetDesc( int nErrCode )
{
	switch( nErrCode )
	{
		CASE_RETURN( RAS_rErrInvalidParam, MMC_FAIL_REASON_INVALID_PARAM );
		CASE_RETURN( RAS_rErrOverflow, MMC_FAIL_REASON_OVERFLOW );
		CASE_RETURN( RAS_rErrDBSetValue, MMC_FAIL_REASON_DB_FAIL );
		CASE_RETURN( RAS_rErrDBGetValue, MMC_FAIL_REASON_DB_FAIL );
		CASE_RETURN( RAS_rErrDBExecute, MMC_FAIL_REASON_DB_FAIL );
		CASE_RETURN( RAS_rErrDBFetch, MMC_FAIL_REASON_DB_FAIL );
		CASE_RETURN( RAS_rErrDBExecUpdate, MMC_FAIL_REASON_DB_FAIL );
		CASE_RETURN( RAS_rErrDBNotFound, MMC_FAIL_REASON_DB_NOT_FOUND );	
		CASE_RETURN( RAS_rErrDBDuplicate, MMC_FAIL_REASON_DB_DUPLICATE );	
		CASE_RETURN( RAS_rErrRegiCreate, MMC_FAIL_REASON_REGI_FAIL );
		CASE_RETURN( RAS_rErrRegiSetValue, MMC_FAIL_REASON_REGI_FAIL );
		CASE_RETURN( RAS_rErrRegiGetValue, MMC_FAIL_REASON_REGI_FAIL );
		CASE_RETURN( RAS_rErrRegiGetEnumKeyValue, MMC_FAIL_REASON_REGI_FAIL );
		CASE_RETURN( RAS_rErrRegiDelete, MMC_FAIL_REASON_REGI_FAIL );
		CASE_RETURN( RAS_rErrRegiKeyExist, MMC_FAIL_REASON_REGI_KEY_EXIST );
		CASE_RETURN( RAS_rErrRegiNotFound, MMC_FAIL_REASON_REGI_NOT_FOUND );
		CASE_DEFAULT_UNKNOWN;
	}
}
